apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-rollout.yaml
  - backend-canary-service.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - network-policies.yaml
  - hpa.yaml

images:
  - name: "052464239829.dkr.ecr.eu-north-1.amazonaws.com/product-crud-backend"
    newTag: "latest"
  - name: "052464239829.dkr.ecr.eu-north-1.amazonaws.com/product-crud-frontend"
    newTag: "latest"
