apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-crud

resources:
  - namespace.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml

images:
  - name: "052464239829.dkr.ecr.eu-north-1.amazonaws.com/product-crud-backend"
    newTag: "20b5b631a10b26e601200a230a610ddd42046039"
  - name: "052464239829.dkr.ecr.eu-north-1.amazonaws.com/product-crud-frontend"
    newTag: "20b5b631a10b26e601200a230a610ddd42046039"

commonAnnotations:
  description: "Product CRUD Application - Managed by ArgoCD"
