apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-crud

resources:
  - namespace.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/postgres.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml

images:
  - name: "052464239829.dkr.ecr.eu-north-1.amazonaws.com/product-crud-backend"
    newTag: "f25137db376fd7ba1fac6a484d4500f977b86d38"
  - name: "052464239829.dkr.ecr.eu-north-1.amazonaws.com/product-crud-frontend"
    newTag: "f25137db376fd7ba1fac6a484d4500f977b86d38"

commonAnnotations:
  description: "Product CRUD Application - Managed by ArgoCD"
